
# Topic to read joistick status
joy: 'joy'
# Buttons list manager
buttons:
    # Define led on off button and parameter reference
    led:
        # Enable/Disable button
        button: 7
        # Topic to send enable/disable message
        topic: 'led_controller/status'
    # Define emergency button for Roboteq controller
    emergency:
        # Enable/Disable button
        button: 3
        # Topic to send enable/disable message
        topic: 'roboteq/emergency_stop'
# Configuration start/stop and next button
audio:
    # Enable disable audio controller
    enable: 7
    # Start/Stop button
    start: 4
    # Next song
    next: 5
    # Set songs
    song:
        init: 'controller/R2D2-init.wav'
        exit: 'controller/R2D2-exit.wav'
# Text to speech
speech:
    # Button text
    button: 6
    # List texts to speech
    text: ['Hello sir, My name is Panther']
