analyzers:
  sound:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Sound
    contains: 'sound_play'
    find_and_remove_prefix: sound_play
    num_items: 1
  imu:
    type: diagnostic_aggregator/GenericAnalyzer
    path: IMU
    contains: 'Imu'
  zed:
    type: diagnostic_aggregator/GenericAnalyzer
    path: ZED
    find_and_remove_prefix: zed2
    contains: 'zed'
    remove_prefix: 'zed2 zed_node'
  motors:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Roboteq
    contains: [ 'Roboteq', 'joint']
